// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RawMessage is a raw encoded JSON value.
 * It implements [Marshaler] and [Unmarshaler] and can
 * be used to delay JSON decoding or precompute a JSON encoding.
 * @typedef {any} RawMessage
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
