// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AdministrationAPI exposes explicit user operations and read-only authority.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @param {string} operation
 * @param {string[] | null} categories
 * @param {string} projectRoot
 * @param {boolean} confirmed
 * @returns {$CancellablePromise<service$0.MaintenanceResult>}
 */
export function Maintain(operation, categories, projectRoot, confirmed) {
    return $Call.ByName("main.AdministrationAPI.Maintain", operation, categories, projectRoot, confirmed);
}

/**
 * @param {string} provider
 * @param {boolean} removeSource
 * @param {boolean} replace
 * @returns {$CancellablePromise<service$0.MigrationResult>}
 */
export function Migrate(provider, removeSource, replace) {
    return $Call.ByName("main.AdministrationAPI.Migrate", provider, removeSource, replace);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetNativeStore(enabled) {
    return $Call.ByName("main.AdministrationAPI.SetNativeStore", enabled);
}

/**
 * @returns {$CancellablePromise<service$0.AdministrationStatus>}
 */
export function Status() {
    return $Call.ByName("main.AdministrationAPI.Status");
}

/**
 * @returns {$CancellablePromise<service$0.DelegationCheck[] | null>}
 */
export function VerifyDelegation() {
    return $Call.ByName("main.AdministrationAPI.VerifyDelegation");
}
