// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CatalogAPI — EngineHost.catalog.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @param {string} name
 * @returns {$CancellablePromise<service$0.BenchmarkDetail>}
 */
export function BenchmarkDetail(name) {
    return $Call.ByName("main.CatalogAPI.BenchmarkDetail", name);
}

/**
 * @returns {$CancellablePromise<string[] | null>}
 */
export function Benchmarks() {
    return $Call.ByName("main.CatalogAPI.Benchmarks");
}

/**
 * @param {string} slug
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGroup(slug) {
    return $Call.ByName("main.CatalogAPI.DeleteGroup", slug);
}

/**
 * @param {string} slug
 * @returns {$CancellablePromise<service$0.GroupDetail>}
 */
export function DuplicateGroup(slug) {
    return $Call.ByName("main.CatalogAPI.DuplicateGroup", slug);
}

/**
 * @param {string} slug
 * @returns {$CancellablePromise<service$0.GroupDetail>}
 */
export function GroupDetail(slug) {
    return $Call.ByName("main.CatalogAPI.GroupDetail", slug);
}

/**
 * @returns {$CancellablePromise<service$0.GroupSummary[] | null>}
 */
export function Groups() {
    return $Call.ByName("main.CatalogAPI.Groups");
}

/**
 * @param {string} slug
 * @param {string[] | null} benchmarks
 * @param {string} renameTo
 * @returns {$CancellablePromise<void>}
 */
export function SaveGroup(slug, benchmarks, renameTo) {
    return $Call.ByName("main.CatalogAPI.SaveGroup", slug, benchmarks, renameTo);
}
