// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FavouritesAPI — EngineHost.favourites.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @returns {$CancellablePromise<service$0.Favourite[] | null>}
 */
export function List() {
    return $Call.ByName("main.FavouritesAPI.List");
}

/**
 * @param {string} routeKey
 * @returns {$CancellablePromise<void>}
 */
export function Pin(routeKey) {
    return $Call.ByName("main.FavouritesAPI.Pin", routeKey);
}

/**
 * @param {string} routeKey
 * @returns {$CancellablePromise<void>}
 */
export function Unpin(routeKey) {
    return $Call.ByName("main.FavouritesAPI.Unpin", routeKey);
}
