// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HarnessesAPI — EngineHost.harnesses.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @param {string} slug
 * @returns {$CancellablePromise<void>}
 */
export function Delete(slug) {
    return $Call.ByName("main.HarnessesAPI.Delete", slug);
}

/**
 * @param {string} slug
 * @param {string} routeKey
 * @param {string} profileSlug
 * @returns {$CancellablePromise<service$0.LaunchResult>}
 */
export function Launch(slug, routeKey, profileSlug) {
    return $Call.ByName("main.HarnessesAPI.Launch", slug, routeKey, profileSlug);
}

/**
 * @returns {$CancellablePromise<service$0.HarnessInfo[] | null>}
 */
export function List() {
    return $Call.ByName("main.HarnessesAPI.List");
}

/**
 * @param {service$0.HarnessInfo} h
 * @returns {$CancellablePromise<void>}
 */
export function Save(h) {
    return $Call.ByName("main.HarnessesAPI.Save", h);
}

/**
 * @param {string} slug
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetAllProviders(slug, on) {
    return $Call.ByName("main.HarnessesAPI.SetAllProviders", slug, on);
}

/**
 * @param {string} slug
 * @param {string} provider
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetProvider(slug, provider, on) {
    return $Call.ByName("main.HarnessesAPI.SetProvider", slug, provider, on);
}
