// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PickAPI — EngineHost.pick.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @returns {$CancellablePromise<service$0.CatalogSummary>}
 */
export function CatalogLine() {
    return $Call.ByName("main.PickAPI.CatalogLine");
}

/**
 * @param {service$0.RankRequest} req
 * @returns {$CancellablePromise<service$0.RankResponse>}
 */
export function Rank(req) {
    return $Call.ByName("main.PickAPI.Rank", req);
}

/**
 * @param {string} profileSlug
 * @param {string} routeKey
 * @returns {$CancellablePromise<void>}
 */
export function RecordPick(profileSlug, routeKey) {
    return $Call.ByName("main.PickAPI.RecordPick", profileSlug, routeKey);
}
