// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfilesAPI — EngineHost.profiles.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @returns {$CancellablePromise<string[] | null>}
 */
export function ComplexityScale() {
    return $Call.ByName("main.ProfilesAPI.ComplexityScale");
}

/**
 * @param {service$0.ProfileDetail} p
 * @returns {$CancellablePromise<void>}
 */
export function Create(p) {
    return $Call.ByName("main.ProfilesAPI.Create", p);
}

/**
 * @param {string} slug
 * @returns {$CancellablePromise<void>}
 */
export function Delete(slug) {
    return $Call.ByName("main.ProfilesAPI.Delete", slug);
}

/**
 * @param {string} slug
 * @returns {$CancellablePromise<service$0.ProfileDetail>}
 */
export function Duplicate(slug) {
    return $Call.ByName("main.ProfilesAPI.Duplicate", slug);
}

/**
 * @param {string} slug
 * @returns {$CancellablePromise<service$0.ProfileDetail>}
 */
export function Get(slug) {
    return $Call.ByName("main.ProfilesAPI.Get", slug);
}

/**
 * @returns {$CancellablePromise<service$0.ProfileSummary[] | null>}
 */
export function List() {
    return $Call.ByName("main.ProfilesAPI.List");
}

/**
 * @param {service$0.ProfileDetail} p
 * @returns {$CancellablePromise<void>}
 */
export function Save(p) {
    return $Call.ByName("main.ProfilesAPI.Save", p);
}
