// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProvidersAPI — EngineHost.providers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<service$0.ProviderDetail>}
 */
export function Detail(id) {
    return $Call.ByName("main.ProvidersAPI.Detail", id);
}

/**
 * @returns {$CancellablePromise<service$0.ProviderInfo[] | null>}
 */
export function List() {
    return $Call.ByName("main.ProvidersAPI.List");
}

/**
 * @param {string[] | null} orderedIds
 * @returns {$CancellablePromise<void>}
 */
export function Reorder(orderedIds) {
    return $Call.ByName("main.ProvidersAPI.Reorder", orderedIds);
}

/**
 * @param {string} id
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetAllRoutes(id, on) {
    return $Call.ByName("main.ProvidersAPI.SetAllRoutes", id, on);
}

/**
 * @param {string} id
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetEnabled(id, on) {
    return $Call.ByName("main.ProvidersAPI.SetEnabled", id, on);
}

/**
 * @param {string} id
 * @param {string} modelId
 * @param {string} reasoning
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetRouteEnabled(id, modelId, reasoning, on) {
    return $Call.ByName("main.ProvidersAPI.SetRouteEnabled", id, modelId, reasoning, on);
}
