// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsAPI — EngineHost.settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @returns {$CancellablePromise<service$0.GUISettings>}
 */
export function Get() {
    return $Call.ByName("main.SettingsAPI.Get");
}

/**
 * @param {service$0.GUISettings} s
 * @returns {$CancellablePromise<void>}
 */
export function Set(s) {
    return $Call.ByName("main.SettingsAPI.Set", s);
}

/**
 * @returns {$CancellablePromise<service$0.ShellSnippets>}
 */
export function ShellSnippets() {
    return $Call.ByName("main.SettingsAPI.ShellSnippets");
}
