// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SignInAPI — EngineHost.signin. OAuth methods drive interactive provider
 * login; SaveAPIKey stores a submitted key outside config.toml.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @param {string} provider
 * @param {string} flowID
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(provider, flowID) {
    return $Call.ByName("main.SignInAPI.Cancel", provider, flowID);
}

/**
 * @param {string} provider
 * @param {string} flowID
 * @param {string} accountName
 * @returns {$CancellablePromise<void>}
 */
export function Confirm(provider, flowID, accountName) {
    return $Call.ByName("main.SignInAPI.Confirm", provider, flowID, accountName);
}

/**
 * @param {string} provider
 * @param {string} accountName
 * @param {string} apiKey
 * @returns {$CancellablePromise<void>}
 */
export function SaveAPIKey(provider, accountName, apiKey) {
    return $Call.ByName("main.SignInAPI.SaveAPIKey", provider, accountName, apiKey);
}

/**
 * @param {string} provider
 * @returns {$CancellablePromise<service$0.SignInStart>}
 */
export function Start(provider) {
    return $Call.ByName("main.SignInAPI.Start", provider);
}

/**
 * @param {string} provider
 * @param {string} flowID
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function SubmitCode(provider, flowID, code) {
    return $Call.ByName("main.SignInAPI.SubmitCode", provider, flowID, code);
}
