// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SignInAPI — EngineHost.signin. Copilot/Codex device login and Claude
 * PKCE paste: Start returns the URL (+ user code when there is one),
 * Confirm waits until approved, SubmitCode delivers a pasted Claude code,
 * Cancel abandons.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @param {string} provider
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(provider) {
    return $Call.ByName("main.SignInAPI.Cancel", provider);
}

/**
 * @param {string} provider
 * @returns {$CancellablePromise<void>}
 */
export function Confirm(provider) {
    return $Call.ByName("main.SignInAPI.Confirm", provider);
}

/**
 * @param {string} provider
 * @returns {$CancellablePromise<service$0.SignInStart>}
 */
export function Start(provider) {
    return $Call.ByName("main.SignInAPI.Start", provider);
}

/**
 * @param {string} provider
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function SubmitCode(provider, code) {
    return $Call.ByName("main.SignInAPI.SubmitCode", provider, code);
}
