// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UsageAPI — EngineHost.usage.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../internal/service/models.js";

/**
 * @returns {$CancellablePromise<service$0.UsageMode>}
 */
export function Mode() {
    return $Call.ByName("main.UsageAPI.Mode");
}

/**
 * @param {string} backend
 * @returns {$CancellablePromise<void>}
 */
export function SetBackend(backend) {
    return $Call.ByName("main.UsageAPI.SetBackend", backend);
}

/**
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetMode(mode) {
    return $Call.ByName("main.UsageAPI.SetMode", mode);
}

/**
 * @param {boolean} force
 * @returns {$CancellablePromise<service$0.UsageDTO[] | null>}
 */
export function Snapshots(force) {
    return $Call.ByName("main.UsageAPI.Snapshots", force);
}
