// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService holds the app plus the popover window so bound methods can
 * show/hide windows, quit, and copy to the clipboard. All methods are
 * idempotent and nil-safe.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CloseSettings hides the settings window (close = hide; the window is
 * never destroyed while the app runs, S03 SPEC §2.5).
 * @returns {$CancellablePromise<void>}
 */
export function CloseSettings() {
    return $Call.ByName("main.WindowService.CloseSettings");
}

/**
 * CopyToClipboard sets the system clipboard to text via the Wails clipboard
 * manager. A nil app is a silent no-op.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function CopyToClipboard(text) {
    return $Call.ByName("main.WindowService.CopyToClipboard", text);
}

/**
 * HidePopover hides the popover, never closing it (S02 SPEC §2.7).
 * @returns {$CancellablePromise<void>}
 */
export function HidePopover() {
    return $Call.ByName("main.WindowService.HidePopover");
}

/**
 * OpenSettings lazily creates (if needed) and shows the settings window.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByName("main.WindowService.OpenSettings");
}

/**
 * Quit terminates the application cleanly.
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByName("main.WindowService.Quit");
}

/**
 * SetPopoverHeight resizes the popover window to the measured natural height
 * of its content, clamped to [320, 620]. The frontend calls this whenever the
 * active view's height changes, which is what keeps the window content-sized
 * like the design's panel instead of stretching a fixed 620 with filler.
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SetPopoverHeight(height) {
    return $Call.ByName("main.WindowService.SetPopoverHeight", height);
}

/**
 * SetTrayPick puts the popover's current pick in the menu bar: the profile it
 * is ranking for, and the model that came out on top.
 * 
 * The host ranks for the menu bar on its own at startup and on catalog/config
 * events, but it cannot see the popover's state — the active profile and the
 * ephemeral weight overrides live in the webview and never reach the engine as
 * config. So the popover pushes what it is showing, and from the first push it
 * owns the title: whatever the user does with the scale or the sliders, the
 * menu bar says the same thing the popover does.
 * @param {string} profileName
 * @param {string} modelName
 * @param {string} reasoning
 * @param {string} provider
 * @returns {$CancellablePromise<void>}
 */
export function SetTrayPick(profileName, modelName, reasoning, provider) {
    return $Call.ByName("main.WindowService.SetTrayPick", profileName, modelName, reasoning, provider);
}
