// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService holds the app plus the popover window so bound methods can
 * show/hide windows, quit, and copy to the clipboard. All methods are
 * idempotent and nil-safe.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CloseSettings hides the settings window (close = hide; the window is
 * never destroyed while the app runs, S03 SPEC §2.5).
 * @returns {$CancellablePromise<void>}
 */
export function CloseSettings() {
    return $Call.ByName("main.WindowService.CloseSettings");
}

/**
 * CopyToClipboard sets the system clipboard to text via the Wails clipboard
 * manager. A nil app is a silent no-op.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function CopyToClipboard(text) {
    return $Call.ByName("main.WindowService.CopyToClipboard", text);
}

/**
 * HidePopover hides the popover, never closing it (S02 SPEC §2.7).
 * @returns {$CancellablePromise<void>}
 */
export function HidePopover() {
    return $Call.ByName("main.WindowService.HidePopover");
}

/**
 * OpenSettings lazily creates (if needed) and shows the settings window.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByName("main.WindowService.OpenSettings");
}

/**
 * Quit terminates the application cleanly.
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByName("main.WindowService.Quit");
}
