// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * BenchRow is one tested benchmark row.
 * @typedef {$models.BenchRow} BenchRow
 */

/**
 * BenchmarkDetail is one benchmark's detail shape.
 * @typedef {$models.BenchmarkDetail} BenchmarkDetail
 */

/**
 * CatalogModel is one distinct catalog identity (scores CSV model name),
 * aggregated across reasoning rows. Intelligence/Cost/Speed are the top
 * reasoning level's tier-1 scores (0–100), nil when that axis is blank.
 * @typedef {$models.CatalogModel} CatalogModel
 */

/**
 * CatalogModelDetail is the model card: catalog identity plus enabled-provider rows.
 * @typedef {$models.CatalogModelDetail} CatalogModelDetail
 */

/**
 * CatalogModelProvider is one enabled provider that serves a catalog model.
 * Costs are USD per 1M tokens from the models.dev cache; nil means no listed price.
 * @typedef {$models.CatalogModelProvider} CatalogModelProvider
 */

/**
 * CatalogSummary counts the live catalog.
 * @typedef {$models.CatalogSummary} CatalogSummary
 */

/**
 * @typedef {$models.Favourite} Favourite
 */

/**
 * GUISettings is the settings-page aggregate for [gui] plus [auth].use_keychain.
 * @typedef {$models.GUISettings} GUISettings
 */

/**
 * GroupBenchmark is one benchmark's membership within a group detail.
 * @typedef {$models.GroupBenchmark} GroupBenchmark
 */

/**
 * GroupDetail is one group's edit/read shape.
 * @typedef {$models.GroupDetail} GroupDetail
 */

/**
 * GroupSummary is one group's list shape.
 * @typedef {$models.GroupSummary} GroupSummary
 */

/**
 * HarnessInfo is one harness's shape.
 * @typedef {$models.HarnessInfo} HarnessInfo
 */

/**
 * LaunchResult is the harness launch outcome.
 * @typedef {$models.LaunchResult} LaunchResult
 */

/**
 * ModelBenchRow is one benchmark result for a (model, reasoning) pair.
 * @typedef {$models.ModelBenchRow} ModelBenchRow
 */

/**
 * ModelScoreDetail is the inverse of BenchmarkDetail: every benchmark
 * (model, reasoning) reports. An unknown or untested pair returns empty Rows,
 * not not_found — Settings always lets you open a catalogue combo.
 * @typedef {$models.ModelScoreDetail} ModelScoreDetail
 */

/**
 * ProfileDetail is the same shape used for editing.
 * @typedef {$models.ProfileDetail} ProfileDetail
 */

/**
 * ProfileSummary describes one profile for lists; ProfileDetail is the same
 * shape used for editing. Weights are ints 0–5 where 0 means "absent/ignored"
 * (the TOML stores only weights 1–5; 0-valued keys are removed on save).
 * CoreShare is the tier-1 share as an integer percent, clamped 10..90, step 5.
 * @typedef {$models.ProfileSummary} ProfileSummary
 */

/**
 * ProviderAccountDTO is one named credential for a provider. Ref is a
 * REFERENCE (env var, file path, keychain service) — never the secret itself.
 * @typedef {$models.ProviderAccountDTO} ProviderAccountDTO
 */

/**
 * ProviderDetail is the provider edit/read shape.
 * @typedef {$models.ProviderDetail} ProviderDetail
 */

/**
 * ProviderInfo is one provider's list/read shape.
 * @typedef {$models.ProviderInfo} ProviderInfo
 */

/**
 * ProviderModel is one provider model with its reasoning levels.
 * @typedef {$models.ProviderModel} ProviderModel
 */

/**
 * RankRequest.Overrides non-nil ⇒ ephemeral ranking: nothing is persisted and
 * history is NOT written. Holds ∈ {3,5,10}; 0 means "use [gui].holds".
 * @typedef {$models.RankRequest} RankRequest
 */

/**
 * RankResponse is a ranked result set.
 * @typedef {$models.RankResponse} RankResponse
 */

/**
 * RankedModel is one ranked candidate.
 * @typedef {$models.RankedModel} RankedModel
 */

/**
 * RouteLevel is one reasoning level of a provider model.
 * @typedef {$models.RouteLevel} RouteLevel
 */

/**
 * ShellSnippets are the copyable setup snippets.
 * @typedef {$models.ShellSnippets} ShellSnippets
 */

/**
 * SignInStart is the Start result: what the user must see to approve.
 * @typedef {$models.SignInStart} SignInStart
 */

/**
 * UsageDTO is a provider's usage snapshot.
 * @typedef {$models.UsageDTO} UsageDTO
 */

/**
 * UsageMode is the current usage toggle and backend.
 * @typedef {$models.UsageMode} UsageMode
 */

/**
 * UsageWindow is one usage window (session|weekly|monthly|provider-specific).
 * @typedef {$models.UsageWindow} UsageWindow
 */
