// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BenchRow is one tested benchmark row.
 * @typedef {Object} BenchRow
 * @property {string} model
 * @property {string} reasoning
 * @property {number} value - raw benchmark result
 * @property {number} norm - value / max * 100, rounded to integer-valued float
 */

/**
 * BenchmarkDetail is one benchmark's detail shape.
 * @typedef {Object} BenchmarkDetail
 * @property {string} name
 * @property {string} note - description; "" when none recorded
 * @property {string[] | null} groups - group slugs containing it
 * @property {BenchRow[] | null} rows - tested rows only, Norm desc by default
 */

/**
 * ModelBenchRow is one benchmark result for a (model, reasoning) pair.
 * @typedef {Object} ModelBenchRow
 * @property {string} name
 * @property {number} value
 * @property {number} norm - value / max * 100 across every tested model
 * @property {string[] | null} groups
 */

/**
 * ModelScoreDetail is the inverse of BenchmarkDetail: every benchmark
 * (model, reasoning) reports.
 * @typedef {Object} ModelScoreDetail
 * @property {string} model
 * @property {string} reasoning
 * @property {ModelBenchRow[] | null} rows
 */

/**
 * CatalogModel is one distinct catalog identity.
 * @typedef {Object} CatalogModel
 * @property {string} model_name
 * @property {string} model_id
 * @property {string[] | null} reasoning
 * @property {number | null} intelligence
 * @property {number | null} cost
 * @property {number | null} speed
 * @property {number} provider_count
 */

/**
 * CatalogSummary counts the live catalog.
 * @typedef {Object} CatalogSummary
 * @property {number} models - distinct (model, reasoning) rows in scores CSV
 * @property {number} providers_on
 * @property {number} harnesses
 */

/**
 * Favourite is one pinned route.
 * @typedef {Object} Favourite
 * @property {string} route_key
 * @property {string} model_name
 * @property {string} route_label - "provider · reasoning" or "no provider · reasoning"
 * @property {boolean} in_range - route still resolvable
 */

/**
 * GUISettings is the settings-page aggregate for [gui] plus [auth].use_keychain.
 * @typedef {Object} GUISettings
 * @property {string} layout - "carousel"|"list"
 * @property {string} default_tab - "profiles"|"sliders"
 * @property {string} weight_control - "step"|"bar"|"slider"
 * @property {number} holds - 3|5|10
 * @property {string} shortcut - "alt+space"|"ctrl+space"|"cmd+shift+m"
 * @property {boolean} show_menu_bar_icon
 * @property {boolean} launch_at_login
 * @property {boolean} copy_command_instead
 * @property {boolean} close_popover_after_launch
 * @property {boolean} auto_update
 * @property {string} auto_update_frequency - "hourly"|"daily"|"weekly"|"monthly"
 * @property {boolean} mcp_server
 * @property {boolean} claude_md_hint
 * @property {boolean} shell_alias
 * @property {boolean} use_keychain - [auth], true prefers OS keychain
 * @property {string} config_path - read-only, display only
 * @property {string} version - read-only, display only
 */

/**
 * GroupBenchmark is one benchmark's membership within a group detail.
 * @typedef {Object} GroupBenchmark
 * @property {string} name
 * @property {boolean} on
 * @property {number} covered - (model,reasoning) rows reporting it
 * @property {number} coverage_total
 */

/**
 * GroupDetail is one group's edit/read shape.
 * @typedef {Object} GroupDetail
 * @property {string} slug
 * @property {boolean} builtin
 * @property {GroupBenchmark[] | null} benchmarks - full catalogue, On marks membership
 */

/**
 * GroupSummary is one group's list shape.
 * @typedef {Object} GroupSummary
 * @property {string} slug
 * @property {boolean} builtin
 * @property {number} benchmark_count
 * @property {number} in_profiles
 */

/**
 * HarnessInfo is one harness's shape.
 * @typedef {Object} HarnessInfo
 * @property {string} slug
 * @property {string} name
 * @property {string} command - template with {model_id}/{reasoning}
 * @property {boolean} builtin
 * @property {boolean} installed - argv[0] found on PATH
 * @property {{ [_ in string]?: boolean } | null} providers - per-harness provider allow-map
 */

/**
 * LaunchResult is the harness launch outcome.
 * @typedef {Object} LaunchResult
 * @property {boolean} copied - true ⇒ frontend puts Command on the clipboard
 * @property {string} command - fully substituted
 */

/**
 * ProfileDetail is the same shape used for editing.
 * @typedef {ProfileSummary} ProfileDetail
 */

/**
 * ProfileSummary describes one profile for lists; ProfileDetail is the same
 * shape used for editing. Weights are ints 0–5 where 0 means "absent/ignored"
 * (the TOML stores only weights 1–5; 0-valued keys are removed on save).
 * CoreShare is the tier-1 share as an integer percent, clamped 10..90, step 5.
 * @typedef {Object} ProfileSummary
 * @property {string} slug
 * @property {string} name
 * @property {boolean} builtin
 * @property {number} core_share
 * @property {{ [_ in string]?: number } | null} tier1_weights - keys ⊆ {intelligence, cost, speed}
 * @property {{ [_ in string]?: number } | null} tier2_weights - keys ⊆ categories ∪ custom group slugs
 * @property {number} picks
 * @property {string} last_used - RFC3339 or ""
 */

/**
 * ProviderAccountDTO is one named credential for a provider. Ref is a
 * REFERENCE (env var, file path, keychain service) — never the secret itself.
 * @typedef {Object} ProviderAccountDTO
 * @property {string} name
 * @property {string} kind - oauth | cookie | token
 * @property {string} ref
 */

/**
 * ProviderDetail is the provider edit/read shape.
 * @typedef {Object} ProviderDetail
 * @property {string} id
 * @property {ProviderModel[] | null} models
 * @property {ProviderAccountDTO[] | null} accounts
 * @property {boolean} builtin - Builtin providers ship a usage adapter and cannot be deleted; the UI disables Delete for them rather than failing the call.
 */

/**
 * ProviderInfo is one provider's list/read shape.
 * @typedef {Object} ProviderInfo
 * @property {string} id
 * @property {boolean} enabled
 * @property {number} priority - 1-based display order
 * @property {string} auth - e.g. "oauth", "device flow", "" when unknown
 * @property {string} limits_line - human summary or "not enabled"
 * @property {number} routes_on
 * @property {number} routes_total
 * @property {number | null} session - used %, nil when unknown
 * @property {number | null} weekly
 * @property {number | null} monthly
 * @property {string} credits
 * @property {string} resets
 * @property {number} accounts - configured account count
 * @property {boolean} builtin - ships a usage adapter -> not deletable
 */

/**
 * ProviderModel is one provider model with its reasoning levels.
 * @typedef {Object} ProviderModel
 * @property {string} model_id
 * @property {string} model_name
 * @property {RouteLevel[] | null} levels
 */

/**
 * RankRequest.Overrides non-nil ⇒ ephemeral ranking: nothing is persisted and
 * history is NOT written. Holds ∈ {3,5,10}; 0 means "use [gui].holds".
 * @typedef {Object} RankRequest
 * @property {string} profile_slug
 * @property {ProfileDetail | null} [overrides]
 * @property {number} holds
 */

/**
 * RankResponse is a ranked result set.
 * @typedef {Object} RankResponse
 * @property {RankedModel[] | null} candidates - top Holds, rank ascending
 * @property {number} total - candidates before truncation
 */

/**
 * RankedModel is one ranked candidate.
 * @typedef {Object} RankedModel
 * @property {number} rank - 1-based
 * @property {string} model_id
 * @property {string} model_name
 * @property {string} provider
 * @property {string} reasoning
 * @property {number} score - already rounded to 2dp
 * @property {string} route_key
 */

/**
 * RouteLevel is one reasoning level of a provider model.
 * @typedef {Object} RouteLevel
 * @property {string} reasoning
 * @property {boolean} enabled
 * @property {boolean} default - level == the model's top reasoning
 */

/**
 * ShellSnippets are the copyable setup snippets.
 * @typedef {Object} ShellSnippets
 * @property {string} alias
 * @property {string} claude_md
 * @property {string} preview - "$ wm <slug>  →  <model_id>  (<provider>)" line
 */

/**
 * SignInStart is the Start result: what the user must see to approve.
 * @typedef {Object} SignInStart
 * @property {string} verification_uri - exact https URL to open
 * @property {string} user_code - code to enter, display-only
 */

/**
 * UsageDTO is a provider's usage snapshot.
 * @typedef {Object} UsageDTO
 * @property {string} provider
 * @property {string} plan
 * @property {string} auth
 * @property {string} confidence - "live"|"cached"|"estimated"
 * @property {boolean} stale
 * @property {UsageWindow[] | null} windows
 * @property {string} credits
 * @property {string} resets
 * @property {string} failure - "" when ok; sanitised message otherwise
 */

/**
 * UsageMode is the current usage toggle and backend.
 * @typedef {Object} UsageMode
 * @property {string} mode
 * @property {string} backend
 */

/**
 * UsageWindow is one usage window (session|weekly|monthly|provider-specific).
 * @typedef {Object} UsageWindow
 * @property {string} id
 * @property {string} label
 * @property {number | null} used_percent - nil when unknown
 * @property {string} reset_hint
 * @property {boolean} unlimited
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
