// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * @typedef {$models.CodexBarInstallation} CodexBarInstallation
 */

/**
 * @typedef {$models.Executable} Executable
 */

/**
 * @typedef {$models.Installation} Installation
 */

/**
 * @typedef {$models.Integrations} Integrations
 */

/**
 * @typedef {$models.Policy} Policy
 */

/**
 * @typedef {$models.Retention} Retention
 */

/**
 * @typedef {$models.Snapshot} Snapshot
 */
