// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @typedef {Object} CodexBarInstallation
 * @property {string} path
 * @property {string} sha256
 * @property {Installation} config
 */

/**
 * @typedef {Object} Executable
 * @property {string} id
 * @property {string} path
 * @property {string} sha256
 * @property {string[] | null} args
 * @property {Installation[] | null} [inputs]
 */

/**
 * @typedef {Object} Installation
 * @property {string} path
 * @property {string} sha256
 */

/**
 * @typedef {Object} Integrations
 * @property {boolean} skill_installation
 * @property {boolean} hook_installation
 * @property {boolean} hook_use
 */

/**
 * @typedef {Object} Policy
 * @property {number} schema_version
 * @property {string} name
 * @property {string[] | null} allowed_providers
 * @property {string[] | null} credential_sources
 * @property {boolean} secure_store_only
 * @property {boolean} identity_free
 * @property {Retention} retention
 * @property {Integrations} integrations
 * @property {Executable[] | null} executables
 * @property {CodexBarInstallation[] | null} codexbar_installations
 * @property {boolean} allow_custom_shell
 * @property {boolean} allow_credential_migration
 */

/**
 * @typedef {Object} Retention
 * @property {number} usage_snapshots_hours
 * @property {number} launch_logs_days
 * @property {number} pick_history_days
 * @property {number} audit_records_days
 */

/**
 * @typedef {Object} Snapshot
 * @property {boolean} managed
 * @property {boolean} required
 * @property {string} [origin]
 * @property {string} [sha256]
 * @property {Policy | null} [policy]
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
