// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function Capabilities() {
    return $Call.ByName("github.com/WD-Mitchell/which-model/pkg/offlinedesktop.API.Capabilities");
}

/**
 * @returns {$CancellablePromise<string[] | null>}
 */
export function Profiles() {
    return $Call.ByName("github.com/WD-Mitchell/which-model/pkg/offlinedesktop.API.Profiles");
}

/**
 * @param {string} profile
 * @param {number} top
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function Rank(profile, top) {
    return $Call.ByName("github.com/WD-Mitchell/which-model/pkg/offlinedesktop.API.Rank", profile, top);
}
