package publish

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DefaultWorkflowName is the committed file name (annex-b §8.2).
const DefaultWorkflowName = "refresh-model-data.yml"

// RepoRoot walks upward from cwd to the nearest ancestor containing ".git".
func RepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := cwd
	for {
		if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no repository root found (no .git ancestor)")
		}
		dir = parent
	}
}

// WorkflowPath returns repoRoot/.github/workflows/refresh-model-data.yml.
func WorkflowPath(repoRoot string) string {
	return filepath.Join(repoRoot, ".github", "workflows", DefaultWorkflowName)
}

// Render returns the workflow YAML bytes (deterministic; exactly one trailing
// "\n"), or nil when !pc.Enabled. Pure function of pc.
func Render(pc *PublishConfig) ([]byte, error) {
	if pc == nil || !pc.Enabled {
		return nil, nil
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# GENERATED by `which-model catalog workflow --write` from [catalog.publish] — do not hand-edit.\n")
	fmt.Fprintf(&b, "name: refresh-model-data\n")
	fmt.Fprintf(&b, "on:\n")
	fmt.Fprintf(&b, "  schedule:\n")
	fmt.Fprintf(&b, "    - cron: %q # %s, per [catalog.publish].schedule\n", pc.Schedule, pc.Timezone)
	fmt.Fprintf(&b, "  workflow_dispatch: {}\n")
	fmt.Fprintf(&b, "permissions:\n")
	fmt.Fprintf(&b, "  contents: write\n")
	if pc.Mode != "direct-push" {
		fmt.Fprintf(&b, "  pull-requests: write\n")
	}
	fmt.Fprintf(&b, "concurrency:\n")
	fmt.Fprintf(&b, "  group: refresh-model-data\n")
	fmt.Fprintf(&b, "  cancel-in-progress: false\n")
	fmt.Fprintf(&b, "jobs:\n")
	fmt.Fprintf(&b, "  refresh:\n")
	fmt.Fprintf(&b, "    runs-on: ubuntu-latest\n")
	fmt.Fprintf(&b, "    timeout-minutes: 15\n")
	if pc.Environment != "" {
		fmt.Fprintf(&b, "    environment: %q\n", pc.Environment)
	}
	fmt.Fprintf(&b, "    strategy:\n")
	fmt.Fprintf(&b, "      fail-fast: false\n")
	fmt.Fprintf(&b, "      matrix:\n")
	fmt.Fprintf(&b, "        branch: [%s] # from [catalog.publish].branches, listed order\n", branchList(pc.Branches))
	fmt.Fprintf(&b, "    steps:\n")
	fmt.Fprintf(&b, "      - uses: actions/checkout@%s # v7.0.1\n", CheckoutPin)
	fmt.Fprintf(&b, "        with:\n")
	fmt.Fprintf(&b, "          ref: ${{ matrix.branch }}\n")
	fmt.Fprintf(&b, "          token: ${{ secrets.CSV_UPDATE_TOKEN || github.token }}\n")
	fmt.Fprintf(&b, "      - run: |\n")
	fmt.Fprintf(&b, "          python3 .daily-update/refresh-model-data.py --output %s\n", shellQuote(pc.RawCSVPath))
	fmt.Fprintf(&b, "        env:\n")
	fmt.Fprintf(&b, "          ARTIFICIAL_ANALYSIS_API: ${{ secrets.ARTIFICIAL_ANALYSIS_API }}\n")
	fmt.Fprintf(&b, "      - run: |\n")
	fmt.Fprintf(&b, "          python3 .daily-update/generate_scores.py --input %s --output %s\n", shellQuote(pc.RawCSVPath), shellQuote(pc.ScoresCSVPath))
	fmt.Fprintf(&b, "          python3 -m unittest discover -s .daily-update/tests -v\n")
	fmt.Fprintf(&b, "      - id: changes\n")
	fmt.Fprintf(&b, "        run: |\n")
	fmt.Fprintf(&b, "          git add -- %s %s\n", shellQuote(pc.RawCSVPath), shellQuote(pc.ScoresCSVPath))
	fmt.Fprintf(&b, "          git diff --cached --quiet || echo \"changed=true\" >> \"$GITHUB_OUTPUT\"\n")
	fmt.Fprintf(&b, "      - if: steps.changes.outputs.changed == 'true'\n")
	fmt.Fprintf(&b, "        run: |\n")
	fmt.Fprintf(&b, "          git -c user.name=\"github-actions[bot]\" -c user.email=\"github-actions[bot]@users.noreply.github.com\" \\\n")
	fmt.Fprintf(&b, "            commit -m %q\n", pc.CommitMessage)
	if pc.Mode == "direct-push" {
		fmt.Fprintf(&b, "      - id: publish\n")
		fmt.Fprintf(&b, "        if: steps.changes.outputs.changed == 'true'\n")
		fmt.Fprintf(&b, "        run: git push origin HEAD:${{ matrix.branch }}\n")
	} else {
		fmt.Fprintf(&b, "      - if: steps.changes.outputs.changed == 'true'\n")
		labels := ""
		for _, l := range pc.PRLabels {
			labels += " --label " + l
		}
		fmt.Fprintf(&b, "        run: |\n")
		fmt.Fprintf(&b, "          head_branch=\"refresh-model-data-${{ github.run_id }}-${{ strategy.job-index }}\"\n")
		fmt.Fprintf(&b, "          git push origin \"HEAD:refs/heads/${head_branch}\"\n")
		fmt.Fprintf(&b, "          gh pr create --base \"${{ matrix.branch }}\" --head \"${head_branch}\" --title %q --body %q%s\n", pc.PRTitle, "Automated catalog refresh.", labels)
		fmt.Fprintf(&b, "        env:\n")
		fmt.Fprintf(&b, "          GH_TOKEN: ${{ secrets.CSV_UPDATE_TOKEN || github.token }}\n")
		if pc.AutoMerge {
			fmt.Fprintf(&b, "      - if: steps.changes.outputs.changed == 'true'\n")
			fmt.Fprintf(&b, "        run: |\n")
			fmt.Fprintf(&b, "          if [ -n \"$CSV_UPDATE_TOKEN\" ]; then\n")
			fmt.Fprintf(&b, "            gh pr review --approve \"refresh-model-data-${{ github.run_id }}-${{ strategy.job-index }}\"\n")
			fmt.Fprintf(&b, "          fi\n")
			fmt.Fprintf(&b, "        env:\n")
			fmt.Fprintf(&b, "          GH_TOKEN: ${{ github.token }}\n")
			fmt.Fprintf(&b, "          CSV_UPDATE_TOKEN: ${{ secrets.CSV_UPDATE_TOKEN }}\n")
			fmt.Fprintf(&b, "      - id: merge\n")
			fmt.Fprintf(&b, "        if: steps.changes.outputs.changed == 'true'\n")
			fmt.Fprintf(&b, "        run: gh pr merge --auto --%s \"refresh-model-data-${{ github.run_id }}-${{ strategy.job-index }}\"\n", pc.MergeMethod)
			fmt.Fprintf(&b, "        env:\n")
			fmt.Fprintf(&b, "          GH_TOKEN: ${{ github.token }}\n")
		}
	}
	fmt.Fprintf(&b, "      - name: Report per-branch outcome\n")
	fmt.Fprintf(&b, "        if: always()\n")
	fmt.Fprintf(&b, "        run: |\n")
	fmt.Fprintf(&b, "          if [ \"${{ steps.changes.outcome }}\" = \"success\" ] && [ \"${{ steps.changes.outputs.changed }}\" != \"true\" ]; then\n")
	fmt.Fprintf(&b, "            echo \"refresh branch ${{ matrix.branch }}: skipped-no-changes\" >> \"$GITHUB_STEP_SUMMARY\"\n")
	if pc.Mode == "direct-push" {
		fmt.Fprintf(&b, "          elif [ \"${{ steps.publish.outcome }}\" = \"success\" ]; then\n")
		fmt.Fprintf(&b, "            echo \"refresh branch ${{ matrix.branch }}: published\" >> \"$GITHUB_STEP_SUMMARY\"\n")
	} else {
		fmt.Fprintf(&b, "          elif [ \"${{ steps.merge.outcome }}\" = \"success\" ]; then\n")
		fmt.Fprintf(&b, "            echo \"refresh branch ${{ matrix.branch }}: auto-merge-enabled\" >> \"$GITHUB_STEP_SUMMARY\"\n")
	}
	fmt.Fprintf(&b, "          else\n")
	fmt.Fprintf(&b, "            echo \"refresh branch ${{ matrix.branch }}: failed\" >> \"$GITHUB_STEP_SUMMARY\"\n")
	fmt.Fprintf(&b, "          fi\n")
	return []byte(b.String()), nil
}

// branchList renders the matrix branch list, quoted in listed order.
func branchList(branches []string) string {
	return `"` + strings.Join(branches, `", "`) + `"`
}

// Write renders pc and writes it to path (0644, MkdirAll parents), or
// removes path when !pc.Enabled. Returns a human summary line (SPEC
// behaviour 9 shapes).
func Write(pc *PublishConfig, path string) (string, error) {
	if !pc.Enabled {
		if _, err := os.Stat(path); os.IsNotExist(err) {
			return "no workflow file present (catalog.publish.enabled = false)", nil
		}
		if err := os.Remove(path); err != nil {
			return "", err
		}
		return "removed " + path + " (catalog.publish.enabled = false)", nil
	}
	b, err := Render(pc)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, b, 0o644); err != nil {
		return "", err
	}
	return fmt.Sprintf("wrote %s (schedule=%q, branches=%v, mode=%s)", path, pc.Schedule, pc.Branches, pc.Mode), nil
}

// DriftError carries the stderr lines (headers + minimal line diff).
type DriftError struct {
	Lines []string
}

func (e *DriftError) Error() string { return strings.Join(e.Lines, "\n") }

// Check renders in memory and byte-compares with path (SPEC behaviour 7).
// Returns nil when in sync (incl. !Enabled and path absent). Returns a
// *DriftError otherwise (missing file, stale file, or byte difference).
func Check(pc *PublishConfig, path string) error {
	if !pc.Enabled {
		if _, err := os.Stat(path); os.IsNotExist(err) {
			return nil
		}
		return &DriftError{Lines: []string{
			"--- " + path + " (committed)",
			"+++ " + path + " (generated from [catalog.publish])",
			"file present but catalog.publish.enabled = false (run which-model catalog workflow --write)",
		}}
	}
	rendered, err := Render(pc)
	if err != nil {
		return err
	}
	committed, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &DriftError{Lines: []string{path + " is missing; run which-model catalog workflow --write"}}
		}
		return err
	}
	if bytes.Equal(rendered, committed) {
		return nil
	}
	return &DriftError{Lines: append(
		[]string{
			"--- " + path + " (committed)",
			"+++ " + path + " (generated from [catalog.publish])",
		},
		lineDiff(strings.Split(string(committed), "\n"), strings.Split(string(rendered), "\n"))...,
	)}
}

// lineDiff returns a deterministic minimal line diff: split both sides on
// "\n" (dropping the final empty element), find the first index where they
// differ, emit "@@ -i+1,n +i+1,m @@" (n/m = lines from i to end of each),
// then -/+ prefixed lines from i to the end of each side.
func lineDiff(a, b []string) []string {
	if n := len(a); n > 0 && a[n-1] == "" {
		a = a[:n-1]
	}
	if n := len(b); n > 0 && b[n-1] == "" {
		b = b[:n-1]
	}
	i := 0
	for i < len(a) && i < len(b) && a[i] == b[i] {
		i++
	}
	n, m := len(a)-i, len(b)-i
	out := []string{fmt.Sprintf("@@ -%d,%d +%d,%d @@", i+1, n, i+1, m)}
	for k := i; k < len(a) || k < len(b); k++ {
		if k < len(a) {
			out = append(out, "-"+a[k])
		}
		if k < len(b) {
			out = append(out, "+"+b[k])
		}
	}
	return out
}

// shellQuote preserves literal shell arguments, including quotes and expansions.
func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
